### ISSUE TITLE
Exception: Git Merge Bindings failed

### ISSUE THREAD

**Issue by Dieterbe** [GitJournal/GitJournal#560] opened 2021-11-19 22:26 UTC
Hi, i'm getting this exception when i'm trying to sync from github (using the android app, pro version). This was working until a few days ago. I didn't change anything on github, my private notes repo is still there.

**Comment by vHanda** [comment] 2021-11-19 22:39
Could you please try after enabling "Dart only Merge" from settings -> experimental.

**Comment by Dieterbe** [comment] 2021-11-20 00:38
I think that worked, yeah. i can confirm that changes from github have been pulled in to the app.  I'm not sure if changes i made on my phone were synced to github though, because i forgot what they were.

**Comment by vHanda** [comment] 2021-12-28 17:11
I'm going to close this for now, as I can't reproduce it. Also, I want to stop using the Git Bindings in January for "merging", so hopefully this won't happen again.

**Closed by vHanda** 2021-12-28 17:11 UTC

**Comment by carlobonamico** [comment] 2022-07-01 12:20
I just reproduced with version 1.85.0+3575.

Enabling Dart Merge did indeed fix the issue.
