### ISSUE TITLE
WYSIWYG/WYSIWYM Markdown Renderer

### ISSUE THREAD

**Issue by alzxjm** [GitJournal/GitJournal#523] opened 2021-07-08 15:36 UTC
## Environment

**App version:**

Mobile and desktop, but mobile especially as there are no great options.

## Description

An editor option in the spirit of either Joplin's [WYSIWYG editor](https://joplinapp.org/rich_text_editor/) or Zettlr's [WYSIWYM editor](https://docs.zettlr.com/en/concepts/wysiwym/). Both of those preserve the underlying Markdown formatting (good for compatibility and future-proofing) but provide a better editing experience, especially on mobile (not that either of those editors are available on mobile).

With Standard Notes one can use the Bold editor, which is also WYSIWYG, though in HTML so the underlying file is not in Markdown. I mention it, however, because it provides a fantastic experience on mobile. Easy formatting, inline image display, etc.

**Images:**   

![Standard Notes Bold Editor on Mobile](https://user-images.githubusercontent.com/15354332/124948258-85798700-dfde-11eb-8448-d556b57a09cf.jpeg)

<img width="1026" alt="Zettlr WYSIWYM Example" src="https://user-images.githubusercontent.com/15354332/124950322-4c421680-dfe0-11eb-8433-d7c62c4d4b04.png">

<img width="499" alt="Screen Shot 2021-07-08 at 11 36 04 AM" src="https://user-images.githubusercontent.com/15354332/124950761-b5c22500-dfe0-11eb-8838-fd25e35de8f4.png">

There are a few examples of what I mean. None of them are as good as what I'm proposing, especially for a mobile experience.

**Comment by jzeneto** [comment] 2021-07-23 23:35
Personally I like very much iA Writer's editor interface. It's simple yet powerful, taking minimal screen space.

**Comment by alzxjm** [comment] 2021-07-24 10:55
> Personally I like very much iA Writer's editor interface. It's simple yet powerful, taking minimal screen space.

I don't care for iA Writer's markdown flavor, but their UI is nice. Joplin's WYSIWYG on desktop is probably my favorite.

**Comment by jzeneto** [comment] 2021-07-26 20:09
Sorry I didn't provide any samples of iA Writer's interface. Here it goes (older version which is free):

![iA Writer partial screenshot](https://user-images.githubusercontent.com/35090091/127052132-3d075b5b-2e75-4839-940a-0713e6583921.jpg)

Perhaps Paste button could be changed for another function, but in general that interface has what's usually needed to edit most markdown files, I think.

**Comment by vHanda** [comment] 2021-07-31 15:36
Hello. I'm closing this as a duplicate of - https://github.com/GitJournal/GitJournal/issues/113

Could you please all vote on that issue?

Also, thank you for filling such a detailed bug report.

**Closed by vHanda** 2021-07-31 15:36 UTC

**Comment by vHanda** [comment] 2021-07-31 23:43
Please could you also subscribe to the issue to get updates. I'll most probably release this, first, as an experimental feature.
