### ISSUE TITLE
Obsidian like image link support 

### ISSUE THREAD

**Issue by 1001ruchka** [GitJournal/GitJournal#350] opened 2020-11-16 23:50 UTC
Please add obsidian like image link support:
![[image-name.jpg]]

**Comment by vHanda** [comment] 2020-11-17 13:06
Closing as duplicate of https://github.com/GitJournal/GitJournal/issues/222

I'm really hoping I can get this done this month - I had been blocked by ios issues for the past week, now I'm finally unblocked, so I'll finish Multi Repo support and then get started with Obsidian Compatibility.

**Closed by vHanda** 2020-11-17 13:06 UTC
