### ISSUE TITLE
Git Journal won't delete files when files are deleted from remote

### ISSUE THREAD

**Issue by kshensovato** [GitJournal/GitJournal#956] opened 2024-01-28 08:45 UTC
I'm using Git Journal to sync with Obsidian (using Obsidian Git plugin) on desktop.
If I delete files from Obsidian, after the file deletion is pushed to GitHub, those files still show up in Git Journal. They are not deleted on Git Journal side.

**Comment by adambro** [comment] 2024-02-12 17:49
Yeah, I've got similar issue. In my case I've moved files `git mv` across directories. GitJournal restored the original notes, so I ended up with duplicate notes: the new one with my additions and the old contents (before move).

**Comment by seadowg** [comment] 2024-03-15 16:57
Having the same problem. Currently I need to remove/readd the repository to honour deletes from the remote.

**Comment by whirledsol** [comment] 2024-03-22 17:31
Also experiencing this as of late.
Would `git rm <file>` work to remove the original files?

**Comment by seadowg** [comment] 2024-04-04 00:00
I'm guessing this is related to #962 and #957

**Comment by vHanda** [comment] 2024-04-19 14:16
Closing this in favor of https://github.com/GitJournal/GitJournal/issues/962

I see what the issue is and how to fix it.

**Closed by vHanda** 2024-04-19 14:16 UTC
