### ISSUE TITLE
More custom filename options

### ISSUE THREAD

**Issue by planetscripton** [GitJournal/GitJournal#204] opened 2020-08-02 22:23 UTC
I really need to set a more customized filename template.

What I need is yyyy-mm-dd-title-of-the-note.md

This is to work with the Jekyll blogging platform.

**Comment by vHanda** [comment] 2020-08-02 22:27
For now you can manually rename the file (when editing, tap on the three dots, and then 'Rename File'). Closing as this is a duplicate of https://github.com/GitJournal/GitJournal/issues/56

I'm not promising 100%, but I think I'll probably get this done this week. I'll just expose a simple templating language, and allow you to go nuts.

**Closed** 2020-08-02 22:27 UTC
