### ISSUE TITLE
Allow spaces in links

### ISSUE THREAD

**Issue by chris-sanders** [GitJournal/GitJournal#613] opened 2022-03-19 15:48 UTC
I'm trying out GitJournal with my existing markdown based note taking workflow and I'm noticing that links do not work if there is a space in the filename. For example I have a link [Home Lab](Home Lab) with the file "Home Lab.md" and the link is not found, other links without a space work fine. Example of a working link [Blogging](Blogging) links to the file "Blogging.md" as expected.

I've been transitioning my notes to a different file name format to decouple them from the note title, but I still have notes that I haven't updated and following existing links would be nice. I don't see why a space would necessarily be excluded maybe it's just something you haven't tested that could be fixed fairly easily?

**Comment by vHanda** [comment] 2022-03-19 16:58
Closing as it's a duplicate of https://github.com/GitJournal/GitJournal/issues/392

Sadly, last time I looked into this, it wasn't trivial. I'll have to fork the underlying markdown parser and change it, since spaces in links are not valid in the official markdown spec.

Please could you vote on that issue?

**Closed by vHanda** 2022-03-19 16:58 UTC
