### ISSUE TITLE
Notes do not sync from repo to phone

### ISSUE THREAD

**Issue by Physmatik** [GitJournal/GitJournal#357] opened 2020-12-05 15:34 UTC
Pretty much the title. I push changes from my desktop to a private GitLab repo, then open GitJournal on my phone and press sync button. It shows the check on the cloud icon (and no error messages), but notes are not synced — there are files in the repo (and desktop repo copy) that I can't see from phone.

**Comment by relston** [comment] 2020-12-08 05:20
I have been experiencing the same issue. There seems to be some bug with how the latest version is pulling. The logs seem to have an error: `Exception: Current Branch null`
Logs:
```
...
{"path":"/data/user/0/io.gitjournal.gitjournal/app_flutter/journal_0/.gitignore","reason":"IgnoreReason.HiddenFile"}}
{"t":1607404568538,"l":"d","msg":"Received Share with App (text): null"}
{"t":1607404569411,"l":"e","msg":"Got Exception","ex":"Exception: Current Branch null","stack":"#0      GitNoteRepository.merge (package:gitjournal/core/git_repo.dart:190) <asynchronous suspension> #1      Repository.syncNotes (package:gitjournal/repository.dart:188) <asynchronous suspension> "}
{"t":1607404569488,"l":"d","msg":"Synced!"}
{"t":1607404569970,"l":"d","msg":"Saving the NotesCache"}
{"t":1607404569975,"l":"i","msg":"Finished loading all the notes"}
{"t":1607404569975,"l":"v","msg":"Ignoring file","p":{"path":"/data/user/0/io.gitjournal.gitjournal/app_flutter/journal_0/.gitignore","reason":"IgnoreReason.HiddenFile"}}
{"t":1607404570019,"l":"d","msg":"Saving the NotesCache"}
{"t":1607404576137,"l":"d","msg":"Event.DrawerSettings"}
{"t":1607404581916,"l":"i","msg":"No log file for 2020-12-06 21:16:21.916840"}
```
@Physmatik are you seeing the same thing?

**Comment by dummifiedme** [comment] 2020-12-18 16:16
Same issue.

**Comment by vHanda** [comment] 2020-12-27 10:08
Closing as duplicate of #361

**Closed by vHanda** 2020-12-27 10:09 UTC
