### ISSUE TITLE
enhancement: use sqlite for indexing

### ISSUE THREAD

**Issue by sanzoghenzo** [GitJournal/GitJournal#21] opened 2019-10-28 21:46 UTC
I'm experiencing long loading time when opening the app with many entries in it (I used my script to import older entries from Day One/Narrate): the app shows the "Why not add your first journal entry?" message for some seconds before showing my entries.

I suggest taking a Notational Velocity-like approach, using a sqlite full text search table to index the files and rely on it for subsequent app loading.

After the first time indexing operation, things are even easier than NV/nvAlt, since we have the git backend that tells us which file have been added/edited/removed on pull, so there's no need to constantly monitor the files.

Full text search can be performed with [sqlite_bm25 package](https://pub.dev/packages/sqlite_bm25).

I don't know flutter to be able to help right away, but I'm happy to help this project grow.

If you're interested in this feature, I can try to implement it.

BTW, can you point me to some helpful guide to quickly get up to speed with dart and flutter?

Thanks and Keep up the good work!

**Comment by vHanda** [comment] 2019-10-29 11:48
Hello.

The problem is that I'm currently loading all files in memory before the user interface is rendered. The code needs to be refactored to only load the visible notes and/or load the rest in the background without waiting.

If with that, we're still too slow, then for sure we should use sqlite or something else. It would also make searching far more efficient.

I'll add some build instructions today/tomorrow so you can easily get this up and running. Till then maybe you want to see how the CI builds the apk, and do something similar.

I'm going to close this bug and open a new one to load the notes asynchronously and not block.

**Closed by vHanda** 2019-10-29 11:48 UTC
