### ISSUE TITLE
Set default branch

### ISSUE THREAD

**Issue by Uzay-G** [GitJournal/GitJournal#367] opened 2020-12-16 08:16 UTC
## Description

When I configured my repo, GitJournal picked a branch that was not the main branch and didn't correspond to the one I was using.

I couldn't find a way to change the remote settings so it pushed to the correct branch.

Is this possible?

Thanks!

**Comment by vHanda** [comment] 2020-12-16 08:17
Closing as duplicate of https://github.com/GitJournal/GitJournal/issues/363

Actively working on it.

**Closed by vHanda** 2020-12-16 08:17 UTC

**Comment by Uzay-G** [comment] 2020-12-16 08:20
Thanks! I'm trying to see if GitJournal would work with knowledge base software I wrote which I am adding a git integration to, [archivy](https://github.com/archivy/archivy), that also uses yaml front matter.

GitJournal looks nice!

**Comment by vHanda** [comment] 2020-12-16 08:24
Archivy looks nice!

Please feel free to open bugs regarding how GitJournal can be more compatible with it. I would like GitJournal to work well with other tools.
