### ISSUE TITLE
make the repository data visible so it can be used also by other apps

### ISSUE THREAD

**Issue by aisbergde** [GitJournal/GitJournal#154] opened 2020-05-29 20:07 UTC
One of your aims is:
>Builds on top of open standards so that it can be easily integrated into your existing workflow.

And that's a great idea. I use markdown and I want to use git. And I found some other apps to work with Markdown on Android. But the GitJournal repository is "very hidden". I can't find how to access itfrom outside GitJournal. Please make it "visible" to other apps, allow to place in a common place.

**Comment by mipro98** [comment] 2020-06-02 18:03
It is currently "not possible" to access the files from outside, unfortunately. They are stored in the private app directory under `/data/data/io.gitjournal.gitjournal/files/journal`. You need root to access it. With root, you might be able to sync this directory to your sdcard or so. But this would be a really hacky solution.

However, GitJournal currently only has to take care of edits on files done by the app itself. When the files are accessible from outside the app, GitJournal has to handle external edits and automatically commit these changes or at least make sure to notify the user about it.

**Comment by vHanda** [comment] 2020-06-02 18:09
What I could do is allow you store the git repo in a place accessible by all apps, and then GitJournal on startup commits any uncommitted changes.

**Comment by aisbergde** [comment] 2020-06-02 23:18
this is what I request.

Regarding the GitJournal automatic push and pull: I think this is the biggest issue when changes happen at the same time in different places. And there could also be situations with bad internet and so on. But regarding this I created another issue.

**Comment by vHanda** [comment] 2020-10-16 10:36
Closing as this is a duplicate of #99. (Almost completely implemented!)

**Closed** 2020-10-17 10:24 UTC
