### ISSUE TITLE
Add to fdroid

### ISSUE THREAD

**Issue by Thewisem** [GitJournal/GitJournal#393] opened 2021-01-17 20:39 UTC
## Environment

**App version:**
**Device information:**
 - OS name and version:
 - Manufacturer:
 - Model:

## Description

**What you'd like to happen:**
I would like to have this app on fdroid store. It would help in reaching more people who are privacy centri.

**Alternatives you've considered:**   

**Images:**

**Comment by vHanda** [comment] 2021-01-17 22:45
Closing as duplicate of #29. The main thing stopping this is adding an independent payment mechanism - It was high on my priority list, but now I'd like to spend some time doing a bit more fun things. Maybe in Feb!

**Closed by vHanda** 2021-01-17 22:45 UTC
