### ISSUE TITLE
Allow merge conflicts to be handled

### ISSUE THREAD

**Issue by Bassmann** [GitJournal/GitJournal#358] opened 2020-12-06 21:29 UTC
## Environment

**App version:**
**Device information:**
 - OS name and version: Android 9
 - Manufacturer: OnePlus
 - Model: 3T

## Description

**What you'd like to happen:**
If the git repo has been changed outside Gitjournal allow merge conflicts to be handled. 
**Alternatives you've considered:**   
Allow simply to checkout the remote (overriding local content) or force push (overriding remote content)
**Images:**

**Comment by vHanda** [comment] 2020-12-11 12:48
Closing as it's a duplicate of https://github.com/GitJournal/GitJournal/issues/241

**Closed by vHanda** 2020-12-11 12:48 UTC
