### ISSUE TITLE
App freezes on enabling "Store repo externally"

### ISSUE THREAD

**Issue by isaif** [GitJournal/GitJournal#356] opened 2020-12-02 11:36 UTC
I tried this on clean install of the app.
1. Enabled "Store repo externally" option
2. Exit the app
3. Start the app again
Three app becomes unresponsive

I am using Android 10.
I have checked that the directory is not getting created in the storage.
Even if create the directory manually, the app remains unresponsive.
By directory I mean "storage/emulated/0/GitJournal/journal" which is shown as "Repo Location"

**Comment by vHanda** [comment] 2020-12-02 12:38
I think it might be cause of Android 10, let me try it in an emulator.

Closing as it's a duplicate of https://github.com/GitJournal/GitJournal/issues/355

**Closed by vHanda** 2020-12-02 12:38 UTC
