### ISSUE TITLE
Unable to store the repository externally

### ISSUE THREAD

**Issue by alensiljak** [GitJournal/GitJournal#428] opened 2021-03-01 16:03 UTC
## Environment

**App version:**  1.74.1+2278 (play store)
**Device information:**
 - OS name and version: Lineage OS 17.1 (Android 10)
 - Manufacturer: Xiaomi
 - Model: Mi 9T

## Description

**Expected behavior:**

The repository stored on Internal Storage, Notes folder (use existing notes).

**Current behavior:**

The app asks for permissions to the selected location (Internal Storage/Notes). Then it changes the location from private "journal" folder to public "journal" folder in `/storage/emulater/0/Android/data/io.gitjournal.gitjournal/files/GitJournal/journal`, but not to the selected location on Internal Storage (`/storage/emulated/0/Notes`).

## Steps to reproduce

1. Go to Settings
2. Turn on Store Repo Externally
3. Select [Internal Storage]/Notes, for example
4. allow access
5. observe the Repo Location setting

## Others 

<details>
  <summary>Logs</summary>

```
16:38:52 Moving repo to /storage/emulated/0/Android/data/io.gitjournal.gitjournal/files
16:38:52 FilePicker: Got /storage/emulated/0/sync/notes/org but it is not writable
16:38:52 ExtStorage: Got /storage/emulated/0 but it is not writable
```
</details>

Based on the log, it seems that the app never tried to change the location to the selected one, but instead just requested/got the Shared Storage permission. The required request is probably [this](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE).

References:

- https://developer.android.com/training/data-storage
- https://developer.android.com/training/data-storage/shared/documents-files
- https://developer.android.com/training/data-storage/shared/documents-files#grant-access-directory
- https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE
- Example: https://android-er.blogspot.com/2015/09/example-of-using-intentactionopendocume.html
- https://stackoverflow.com/questions/54322030/storage-permission-in-flutter
- https://github.com/flutter/flutter/issues/63282
- https://stackoverflow.com/questions/50561737/getting-permission-to-the-external-storage-file-provider-plugin

**Comment by MisterY** [comment] 2021-03-01 16:20
This one describes the situation to the point:

https://stackoverflow.com/questions/58075432/how-to-get-files-from-external-storage-in-flutter

**Comment by vHanda** [comment] 2021-03-03 12:21
Closing this in favor of https://github.com/GitJournal/GitJournal/issues/377 . Thank you for providing all the documentation. I'm sure it'll help me figure out what I'm doing wrong.

**Comment by MisterY** [comment] 2021-03-05 09:31
This can be reproduced in the emulator, also:
![image](https://user-images.githubusercontent.com/462445/110096118-e3326400-7d9d-11eb-90da-a15b98bca326.png)

**Comment by vHanda** [comment] 2021-03-05 09:33
Yup. In my device as well. I just don't know how to fix it. It's a permissions issue. GitJournal cannot write in the path provided by the user.

**Comment by MisterY** [comment] 2021-03-05 09:35
I'm trying to look into that, as an exercise. Learning where the link is between the setting and the file picker.

**Comment by MisterY** [comment] 2021-03-05 09:36
The path_provider package is used:

![image](https://user-images.githubusercontent.com/462445/110096794-9ac77600-7d9e-11eb-93ea-bfc974b83b01.png)

As the answer on SO states:

> To get /storage/emulated/0/, you can used a Third-party package ext_storage. Below code will return your desired Directory path

**Comment by MisterY** [comment] 2021-03-05 09:59
https://github.com/Baseflow/flutter-permission-handler/issues/435

**Comment by orbanbalage** [comment] 2021-08-18 09:01
I still seem to have this issue:

`10:35:09 RepoPath: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal

{"t":1629275514208,"l":"i","msg":"--------------------------------"}
{"t":1629275514208,"l":"i","msg":"--------------------------------"}
{"t":1629275514208,"l":"i","msg":"--------------------------------"}
{"t":1629275514209,"l":"i","msg":"--------- App Launched ---------"}
{"t":1629275514209,"l":"i","msg":"--------------------------------"}
{"t":1629275514209,"l":"i","msg":"--------------------------------"}
{"t":1629275514209,"l":"i","msg":"--------------------------------"}
{"t":1629275514209,"l":"i","msg":"AppSetting {onBoardingCompleted: true, collectUsageStatistics: true, collectCrashReports: true, version: 0, proMode: false, validateProMode: true, proExpirationDate: , debugLogLevel: v, experimentalFs: false, experimentalMarkdownToolbar: false, experimentalGraphView: false, experimentalZeroConf: false, experimentalAccounts: false, experimentalGitMerge: false, experimentalGitOps: false}"}
{"t":1629275514230,"l":"i","msg":"Running on Android","p":{"id":"RRC31.Q1-3-56","host":"ilclbld177","tags":"release-keys","type":"user","model":"moto g(30)","board":"caprip","brand":"motorola","device":"caprip","product":"caprip_retailen","display":"RRC31.Q1-3-56","hardware":"qcom","androidId":"fd33e7290477ecea","bootloader":"MBM-3.0-caprip_retail-7d6811cfd7e-210628","version":{"baseOS":"","sdkInt":30,"release":"11","codename":"REL","incremental":"0aa0d","previewSdkInt":0,"securityPatch":"2021-06-01"},"fingerprint":"motorola/caprip_retailen/caprip:11/RRC31.Q1-3-56/0aa0d:user/release-keys","manufacturer":"motorola","supportedAbis":["arm64-v8a","armeabi-v7a","armeabi"],"systemFeatures":["android.hardware.sensor.proximity","com.motorola.software.game_mode","android.hardware.sensor.accelerometer","android.software.controls","android.hardware.faketouch","com.motorola.software.audiofx","com.google.android.feature.D2D_CABLE_MIGRATION_FEATURE","android.hardware.usb.accessory","android.hardware.telephony.cdma","android.software.backup","com.motorola.software.fmradioservice","android.hardware.touchscreen","android.hardware.touchscreen.multitouch","android.software.print","com.motorola.camera3.caprip","android.software.activities_on_secondary_displays","android.software.voice_recognizers","com.google.lens.feature.CAMERA_INTEGRATION","android.software.picture_in_picture","android.hardware.fingerprint","android.hardware.sensor.gyroscope","android.software.vulkan.deqp.level","android.software.cant_save_state","com.motorola.camera3","com.motorola.appforecast","com.motorola.motolivewallpaper","android.hardware.opengles.aep","com.motorola.motodisplay.6.0","com.motorola.faceunlock","android.hardware.bluetooth","com.summit.motorola.rcs.up","android.hardware.camera.autofocus","android.hardware.telephony.gsm","android.hardware.telephony.ims","com.motorola.software.guideme","android.software.incremental_delivery","android.software.sip.voip","com.motorola.photoeditor","com.motorola.timeweatherwidget","android.hardware.usb.host","android.hardware.audio.output","android.software.verified_boot","android.hardware.camera.flash","android.hardware.camera.front","android.hardware.se.omapi.uicc","android.hardware.screen.portrait","com.motorola.motodisplay.doze.glimpse","com.google.android.feature.DPS","android.hardware.nfc","com.google.android.feature.TURBO_PRELOAD","com.nxp.mifare","android.hardware.sensor.stepdetector","android.software.home_screen","android.hardware.microphone","android.software.autofill","android.software.securely_removes_users","com.google.preload_photos","android.hardware.bluetooth_le","com.motorola.software.notification","android.hardware.touchscreen.multitouch.jazzhand","android.software.app_widgets","android.software.input_methods","android.hardware.sensor.light","android.hardware.vulkan.version","android.software.companion_device_setup","com.google.android.feature.EEA_V2_DEVICE","android.software.device_admin","com.google.android.feature.WELLBEING","android.hardware.wifi.passpoint","android.hardware.camera","com.google.android.feature.ZERO_TOUCH","android.hardware.screen.landscape","com.motorola.software.sprint.hidden_menu","com.google.android.feature.AER_OPTIMIZED","android.hardware.ram.normal","com.summit.motorola.rcs.up.tmo","android.software.managed_users","com.motorola.help","com.motorola.maya","com.motorola.moto","android.software.webview","android.hardware.sensor.stepcounter","android.hardware.camera.capability.manual_post_processing","com.motorola.moto.uirefresh","android.hardware.camera.any","android.hardware.camera.capability.raw","android.hardware.vulkan.compute","com.google.android.apps.dialer.call_recording_audio","android.software.connectionservice","android.hardware.touchscreen.multitouch.distinct","android.hardware.location.network","android.software.cts","android.software.sip","android.hardware.camera.capability.manual_sensor","android.software.app_enumeration","com.google.android.apps.dialer.SUPPORTED","android.hardware.camera.level.full","com.motorola.msimsettings","com.google.android.feature.EEA_DEVICE","android.hardware.wifi.direct","android.software.live_wallpaper","com.motorola.launcher3.twoline","com.motorola.launcher3","android.software.ipsec_tunnels","com.google.android.paid.chrome","com.motorola.actions","android.hardware.nfc.uicc","android.hardware.location.gps","android.software.midi","com.motorola.camera3.content.ai","android.hardware.nfc.any","android.hardware.nfc.hce","com.motorola.easyprefix","android.hardware.wifi","android.hardware.location","com.google.android.paid.search","android.hardware.vulkan.level","com.google.android.feature.PREMIER_TIER","com.uros.software.goodspeed","android.software.secure_lock_screen","android.hardware.biometrics.face","android.hardware.telephony","android.software.file_based_encryption",null],"isPhysicalDevice":true,"supported32BitAbis":["armeabi-v7a","armeabi"],"supported64BitAbis":["arm64-v8a"]}}
{"t":1629275514232,"l":"i","msg":"App Version: 1.79.1"}
{"t":1629275514232,"l":"i","msg":"App Build Number: 2747"}
{"t":1629275514232,"l":"d","msg":"Event.AppUpdate","p":{"version":"1.79.1","previous_app_version":"1.78.2","app_name":"GitJournal","package_name":"io.gitjournal.gitjournal","build_number":"2747"}}
{"t":1629275514253,"l":"d","msg":"Analytics Collection: true"}
{"t":1629275514264,"l":"i","msg":"Repo Ids [0]"}
{"t":1629275514264,"l":"i","msg":"Current Id 0"}
{"t":1629275514264,"l":"i","msg":"StorageConfig {folderName: journal, storeInternally: false, storageLocation: /storage/emulated/0/GitJournal}"}
{"t":1629275514265,"l":"i","msg":"FolderConfig {noteFileNameFormat: FromTitle, journalNoteFileNameFormat: FromTitle, yamlModifiedKey: modified, yamlCreatedKey: created, yamlTagsKey: tags, yamlHeaderEnabled: true, defaultEditor: Markdown, defaultView: Standard, sortingField: Modified, sortingOrder: desc, showNoteSummary: true, folderViewHeaderType: TitleGenerated, imageLocationSpec: ., titleSettings: h1, inlineTagPrefixes: #}"}
{"t":1629275514265,"l":"i","msg":"GitConfig {gitAuthor: true, gitAuthorEmail: true, sshPublicKey: true, sshPrivateKey: true, sshPassword: false}"}
{"t":1629275514265,"l":"i","msg":"Settings {customMetaData: , defaultNewNoteFolderSpec: false, journalEditordefaultNewNoteFolderSpec: , journalEditorSingleNote: false, remoteSyncFrequency: automatic, version: 3, markdownDefaultView: Last Used, markdownLastUsedView: View, homeScreen: all_notes, theme: default, zenMode: false, swipeToDelete: true, emojiParser: true, bottomMenuBar: true, confirmDelete: true}"}
{"t":1629275514265,"l":"i","msg":"Loading Repo at path /storage/emulated/0/GitJournal/journal"}
{"t":1629275514320,"l":"i","msg":"Branch master"}
{"t":1629275514321,"l":"d","msg":"Not syncing because RemoteRepo not configured"}
{"t":1629275514324,"l":"i","msg":"confirmProPurchaseBoot: Pro Mode is false"}
{"t":1629275514387,"l":"d","msg":"Received Share with App (media): []"}
{"t":1629275514519,"l":"i","msg":"Notes Cache Loaded: 4 items"}
{"t":1629275514521,"l":"i","msg":"Finished loading the notes cache"}
{"t":1629275514598,"l":"i","msg":"Notes Cache saving: 4 items"}
{"t":1629275514626,"l":"i","msg":"Finished loading all the notes"}
{"t":1629275517897,"l":"d","msg":"Event.DrawerSetupGitHost"}
{"t":1629275521276,"l":"d","msg":"githostsetup_button_click GitLab"}
{"t":1629275521276,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"GitLab","icon_url":"assets/icon/gitlab-icon.png"}}
{"t":1629275522630,"l":"d","msg":"githostsetup_button_click Setup Automatically"}
{"t":1629275522631,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Setup Automatically","icon_url":""}}
{"t":1629275523743,"l":"d","msg":"githostsetup_button_click Authorize GitJournal"}
{"t":1629275523743,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Authorize GitJournal","icon_url":""}}
{"t":1629275523744,"l":"d","msg":"Starting autoconfigure"}
{"t":1629275523744,"l":"d","msg":"GitLab: Installed Handler"}
{"t":1629275691227,"l":"d","msg":"GitLab: Called onUrl with {URL: gitjournal://login.oauth2#access_token=cc876be49ab98224fbbd91f629921ebaa5224881ee82f69a828060af53278239&token_type=Bearer&state=itobtelxnf}"}
{"t":1629275691229,"l":"d","msg":"GitHost Initalized: GitHostType.GitLab"}
{"t":1629275691830,"l":"i","msg":"Got User Info: UserInfo{name: \"orbanbalage\", email: \"orbanbalage@gmail.com\", username: \"orbanbalage\"}"}
{"t":1629275691835,"l":"d","msg":"Starting RepoSelector"}
{"t":1629275691845,"l":"d","msg":"Starting RepoSelector"}
{"t":1629275701503,"l":"d","msg":"githostsetup_button_click Next"}
{"t":1629275701504,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Next","icon_url":""}}
{"t":1629275701505,"l":"d","msg":"Starting autoconfigure copletion"}
{"t":1629275701505,"l":"i","msg":"Generating SSH Key"}
{"t":1629275708556,"l":"i","msg":"Generating KeyPair took: 0:00:07.050502"}
{"t":1629275708556,"l":"d","msg":"Keys Dir: [/data/user/0/io.gitjournal.gitjournal/code_cache/keysVAGIOG/id_rsa, /data/user/0/io.gitjournal.gitjournal/code_cache/keysVAGIOG/id_rsa.pub]"}
{"t":1629275708561,"l":"i","msg":"Adding as a deploy key"}
{"t":1629275709608,"l":"d","msg":"GitLab addDeployKey: {\"id\":7838732,\"title\":\"GitJournal\",\"created_at\":\"2021-08-18T08:35:10.165Z\",\"expires_at\":null,\"key\":\"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDTOjH/14HnrkbUTE0Rmp1YKFdMT5ge3GAQ6tPppgWwwc/F2QX6hWOJpkj0X8jnpUSIJ8GktALyXuaNpML0O5dqqUcmTf7XyBIK0KuStq1y3Hdv/4CvK6OMENtqM8E9XTSWZW+Svvqpn50gtaTxx4D/1LBgm8UnW+Tvd25O1h05RZ12dMQg+J9BjgMkA0nykSSkFyMMPHPP5I8Qi0xkpIF/yY1Q6Mp2U9lUIoMm33pcjXmnzdaG9fRCxC+KBotIjT/n5Es2FGXX3rLFt16DqGZApO5SFDlrIGMMJITp32H22uLIht+ivACpc8v1igEkXuQ54lwwQOAEzHFYDixstw/yh6cWggStrgtVtvNjWUddYe113UFl1pZnZiAnLpotjhS/Km4l6fEkB36x02O9Ibm6UBhiq3Rr/KCyCWaOGNahPswgZ7Nj49DV81ABuQqxHarcmbDjQNOkem3f/HcV81CzdW9sMPBdrnjAjev6gbkLWcjjZdQtZTijvbhn+wUd9weTaoY1iQofPo+ShHMHSjTvtB9VDufr/FcgAXzZmkWh3IJMuHaOi/+zrRx3fvySZuvSgWmLPWwKTQjsWQZhH9LDvLBrmdBam33rThmBePvZqnYHHRMnfGMQBjvQRgPliOrwNUbg1bw7eiTPXuBNFs81GoSn52wemYPsS2dVKc9iQ== GitJournal\",\"can_push\":true}"}
{"t":1629275709609,"l":"i","msg":"RepoPath: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal"}
{"t":1629275709618,"l":"e","msg":"Failed to clone","ex":"Not a Git Repository: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":[{"uri":"package:dart_git/utils/result.dart","line":11,"member":"new Result.fail","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 11","package":"dart_git"},{"uri":"package:dart_git/git.dart","line":88,"member":"GitRepository.load","isCore":false,"library":"package:dart_git/git.dart","location":"package:dart_git/git.dart 88","package":"dart_git"},{"uri":"package:dart_git/utils/result.dart","line":65,"member":"ResultFuture.getOrThrow","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 65","package":"dart_git"},{"uri":"package:gitjournal/setup/clone.dart","line":51,"member":"cloneRemotePluggable","isCore":false,"library":"package:gitjournal/setup/clone.dart","location":"package:gitjournal/setup/clone.dart 51","package":"gitjournal"},{"uri":"package:dart_git/utils/result.dart","line":49,"member":"catchAll","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 49","package":"dart_git"},{"uri":"package:gitjournal/setup/screens.dart","line":563,"member":"GitHostSetupScreenState._startGitClone","isCore":false,"library":"package:gitjournal/setup/screens.dart","location":"package:gitjournal/setup/screens.dart 563","package":"gitjournal"}]}
{"t":1629275709637,"l":"d","msg":"Event.GitHostSetupGitCloneError","p":{"error":"Not a Git Repository: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal"}}
{"t":1629276171985,"l":"d","msg":"Starting RepoSelector"}
{"t":1629276180997,"l":"i","msg":"Log file /data/user/0/io.gitjournal.gitjournal/cache/logs/2021-08-17.jsonl not found"}
{"t":1629276191867,"l":"d","msg":"Event.DrawerBugReport"}
{"t":1629276193904,"l":"d","msg":"Event.DrawerSettings"}
{"t":1629276202678,"l":"i","msg":"Old Path: /storage/emulated/0/GitJournal/journal"}
{"t":1629276202678,"l":"i","msg":"New Path: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal"}
{"t":1629276203999,"l":"i","msg":"Notes Cache saving: 4 items"}
{"t":1629276212037,"l":"i","msg":"No log file for 2021-08-17"}
{"t":1629276256669,"l":"d","msg":"Event.DrawerSetupGitHost"}
{"t":1629276258882,"l":"d","msg":"githostsetup_button_click GitHub"}
{"t":1629276258883,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"GitHub","icon_url":"assets/icon/github-icon.png"}}
{"t":1629276260731,"l":"d","msg":"githostsetup_button_click GitLab"}
{"t":1629276260731,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"GitLab","icon_url":"assets/icon/gitlab-icon.png"}}
{"t":1629276261490,"l":"d","msg":"githostsetup_button_click Setup Automatically"}
{"t":1629276261491,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Setup Automatically","icon_url":""}}
{"t":1629276262349,"l":"d","msg":"githostsetup_button_click Authorize GitJournal"}
{"t":1629276262349,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Authorize GitJournal","icon_url":""}}
{"t":1629276262350,"l":"d","msg":"Starting autoconfigure"}
{"t":1629276262350,"l":"d","msg":"GitLab: Installed Handler"}
{"t":1629276263481,"l":"d","msg":"GitLab: Called onUrl with {URL: gitjournal://login.oauth2#access_token=cc876be49ab98224fbbd91f629921ebaa5224881ee82f69a828060af53278239&token_type=Bearer&state=%5CxbjfwZwnv}"}
{"t":1629276263481,"l":"d","msg":"GitHost Initalized: GitHostType.GitLab"}
{"t":1629276263940,"l":"i","msg":"Got User Info: UserInfo{name: \"orbanbalage\", email: \"orbanbalage@gmail.com\", username: \"orbanbalage\"}"}
{"t":1629276263947,"l":"d","msg":"Starting RepoSelector"}
{"t":1629276263961,"l":"d","msg":"Starting RepoSelector"}
{"t":1629276266959,"l":"d","msg":"githostsetup_button_click Next"}
{"t":1629276266960,"l":"d","msg":"Event.GitHostSetupButtonClick","p":{"text":"Next","icon_url":""}}
{"t":1629276266960,"l":"d","msg":"Starting autoconfigure copletion"}
{"t":1629276266960,"l":"i","msg":"Generating SSH Key"}
{"t":1629276268547,"l":"i","msg":"Generating KeyPair took: 0:00:01.586740"}
{"t":1629276268548,"l":"d","msg":"Keys Dir: [/data/user/0/io.gitjournal.gitjournal/code_cache/keysIYYZWJ/id_rsa, /data/user/0/io.gitjournal.gitjournal/code_cache/keysIYYZWJ/id_rsa.pub]"}
{"t":1629276268550,"l":"i","msg":"Adding as a deploy key"}
{"t":1629276269117,"l":"d","msg":"GitLab addDeployKey: {\"id\":7838789,\"title\":\"GitJournal\",\"created_at\":\"2021-08-18T08:44:29.690Z\",\"expires_at\":null,\"key\":\"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDhZctTxpR2YdPRBcYbus8ormTqKTNOLY7ISCMmMHqP/tg9dNpeq6vJQXo+GpnUIk4tiKrf23Bz90OppH/dtnz6Y8a3TGqaDrBvnQG1DnshsZ9cZjz7r3puAQuZ2HDkvNHdWWKtZBGm3OJPlMk7jGXPCdnI23Dal5/QNOrDdr2C4Ftm20V9iphDKy8Nws1iF11p9MRXFbNxgQ1C/lkNl4MThUtsd3vHH6zZqPjin/V/W01h1UK4b62ARONSNSIaWncyYTweQP2Ij6a1IIg8F9wAEMkHYaWEXIR420gim05/Fbn/OWPQ8wEAs7rZ+Z3Y3VHKgJvqruQhYWM8r4cdcYduteAha+fbqPdXY+KAxrsXm0zZ3vTO36cUatU2qhj1kbLqxr2DxBBc6sLZY/UX1VdU4DrnBnakETHDxxMfa9j+s0YZjwbuBX9W4xcM5Z3yIFyiGIY6FN6cY6PxrmAPgu2L/ZfRvoS+b1k47QwrhXh3L7yW9Wg2JCm0ilwVnj/wbkec6nhaZ9NeAp3BUP937rKy1dkPciu4Ctfu+VWACndbNvMzYGDayqHX8HIPznndXgynAz11nk74iKsnmJiNQBdYj9QnfGBk3qhlIoy5L3xeDxzDUTWX5FTF5abtFcLh8r/klFKdiTLLjW2R/Dn31/JJVtnoG1Vn5xfzlzxKZsEJCQ== GitJournal\",\"can_push\":true}"}
{"t":1629276269117,"l":"i","msg":"RepoPath: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal"}
{"t":1629276274135,"l":"w","msg":"Could not fetch git main branch","ex":"GitException: Unknown Error"}
{"t":1629276274147,"l":"i","msg":"Using remote branch: master"}
{"t":1629276274158,"l":"i","msg":"Local branches [master]"}
{"t":1629276274158,"l":"i","msg":"Completing - localBranch: master"}
{"t":1629276274228,"l":"d","msg":"Event.GitHostSetupComplete","p":{"host_type":"GitLab","provider_choice":"KnownProvider","setup_manner":"Auto","key_generation":"Unknown"}}
{"t":1629276274228,"l":"i","msg":"Renaming /data/user/0/io.gitjournal.gitjournal/app_flutter/journal --> /data/user/0/io.gitjournal.gitjournal/app_flutter/notes"}
{"t":1629276274230,"l":"i","msg":"calling onComplete notes origin"}
{"t":1629276274230,"l":"i","msg":"repoPath: /data/user/0/io.gitjournal.gitjournal/app_flutter/notes"}
{"t":1629276274305,"l":"d","msg":"Event.RepoSynced"}
{"t":1629276274340,"l":"i","msg":"Notes Cache saving: 4 items"}
{"t":1629276274345,"l":"e","msg":"numChanges","ex":"GitRefNotFound: refs/remotes/origin/master","stack":[{"uri":"package:dart_git/utils/result.dart","line":21,"member":"Result.getOrThrow","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 21","package":"dart_git"},{"uri":"package:dart_git/utils/result.dart","line":66,"member":"ResultFuture.getOrThrow","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 66","package":"dart_git"},{"uri":"package:gitjournal/core/git_repo.dart","line":322,"member":"GitNoteRepository.numChanges","isCore":false,"library":"package:gitjournal/core/git_repo.dart","location":"package:gitjournal/core/git_repo.dart 322","package":"gitjournal"},{"uri":"package:gitjournal/repository.dart","line":186,"member":"GitJournalRepo._loadNotes.<fn>","isCore":false,"library":"package:gitjournal/repository.dart","location":"package:gitjournal/repository.dart 186","package":"gitjournal"},{"uri":"package:synchronized/src/basic_lock.dart","line":33,"member":"BasicLock.synchronized","isCore":false,"library":"package:synchronized/src/basic_lock.dart","location":"package:synchronized/src/basic_lock.dart 33","package":"synchronized"}]}
{"t":1629276276821,"l":"e","msg":"Failed to get remote refs","ex":"GitRefNotFound: refs/remotes/origin/master","stack":[{"uri":"package:dart_git/utils/result.dart","line":11,"member":"new Result.fail","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 11","package":"dart_git"},{"uri":"package:dart_git/storage/reference_storage_fs.dart","line":34,"member":"ReferenceStorageFS.reference","isCore":false,"library":"package:dart_git/storage/reference_storage_fs.dart","location":"package:dart_git/storage/reference_storage_fs.dart 34","package":"dart_git"},{"uri":"package:dart_git/utils/result.dart","line":49,"member":"catchAll","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 49","package":"dart_git"},{"uri":"package:gitjournal/core/git_repo.dart","line":247,"member":"GitNoteRepository._merge","isCore":false,"library":"package:gitjournal/core/git_repo.dart","location":"package:gitjournal/core/git_repo.dart 247","package":"gitjournal"},{"uri":"package:dart_git/utils/result.dart","line":49,"member":"catchAll","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 49","package":"dart_git"},{"uri":"package:gitjournal/repository.dart","line":206,"member":"GitJournalRepo.syncNotes","isCore":false,"library":"package:gitjournal/repository.dart","location":"package:gitjournal/repository.dart 206","package":"gitjournal"}]}
{"t":1629276276839,"l":"i","msg":"Notes Cache saving: 4 items"}
{"t":1629276276845,"l":"e","msg":"Can Push","ex":"GitRefNotFound: refs/remotes/origin/master","stack":[{"uri":"package:dart_git/utils/result.dart","line":21,"member":"Result.getOrThrow","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 21","package":"dart_git"},{"uri":"package:dart_git/utils/result.dart","line":66,"member":"ResultFuture.getOrThrow","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 66","package":"dart_git"},{"uri":"package:gitjournal/core/git_repo.dart","line":282,"member":"GitNoteRepository.push","isCore":false,"library":"package:gitjournal/core/git_repo.dart","location":"package:gitjournal/core/git_repo.dart 282","package":"gitjournal"},{"uri":"package:gitjournal/repository.dart","line":220,"member":"GitJournalRepo.syncNotes","isCore":false,"library":"package:gitjournal/repository.dart","location":"package:gitjournal/repository.dart 220","package":"gitjournal"}]}
{"t":1629276276863,"l":"e","msg":"numChanges","ex":"GitRefNotFound: refs/remotes/origin/master","stack":[{"uri":"package:dart_git/utils/result.dart","line":21,"member":"Result.getOrThrow","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 21","package":"dart_git"},{"uri":"package:dart_git/utils/result.dart","line":66,"member":"ResultFuture.getOrThrow","isCore":false,"library":"package:dart_git/utils/result.dart","location":"package:dart_git/utils/result.dart 66","package":"dart_git"},{"uri":"package:gitjournal/core/git_repo.dart","line":322,"member":"GitNoteRepository.numChanges","isCore":false,"library":"package:gitjournal/core/git_repo.dart","location":"package:gitjournal/core/git_repo.dart 322","package":"gitjournal"},{"uri":"package:gitjournal/repository.dart","line":186,"member":"GitJournalRepo._loadNotes.<fn>","isCore":false,"library":"package:gitjournal/repository.dart","location":"package:gitjournal/repository.dart 186","package":"gitjournal"},{"uri":"package:synchronized/src/basic_lock.dart","line":33,"member":"BasicLock.synchronized","isCore":false,"library":"package:synchronized/src/basic_lock.dart","location":"package:synchronized/src/basic_lock.dart 33","package":"synchronized"}]}
{"t":1629276279907,"l":"d","msg":"Synced!"}
{"t":1629276459885,"l":"i","msg":"Routing from / -> /folders"}
{"t":1629276989446,"l":"d","msg":"Event.DrawerSettings"}
{"t":1629277000684,"l":"i","msg":"No log file for 2021-08-17"}

10:35:09 Event.GitHostSetupGitCloneError
         error: Not a Git Repository: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal

`

**Comment by tonydiep** [comment] 2022-03-25 17:29
I'm experiencing this Mar 2022  Any workaround?

**Comment by arnoo** [comment] 2022-06-14 16:35
I'm also still having this issue. Looking at the app informations page in android settings, it says Gitjournal has "media files access only".  This is by contrast to some other apps which have acces to "all files".

**Comment by spidermatt99** [comment] 2022-06-21 02:10
I am encountering the same problem on the Pixel 6 / Android 12. Any way around this?

**Comment by chrisfgonzales** [comment] 2022-07-06 15:04
I'm encountering the same issue on a Samsung Galaxy Ultra 22 and a Samsung Tab S6

**Comment by jackkinsey** [comment] 2022-07-11 20:53
I'm experiencing this issue on a OnePlus 6T / LineageOS 18 (Android 11).

**Comment by mathisgauthey** [comment] 2022-07-27 08:34
Hi there, I have the same issue as stated bellow in my Pixel 4A 5G from #377 : 
_"I just noticed that GitJournal sets the repo location to /storage/emulated/0/Android/data/io.gitjournal/files/GitJournal/journal and not to the directory that I created and selected/granted permissions for (/storage/emulated/0/notes in this case)."_

**Comment by vHanda** [comment] 2022-11-20 20:12
Marking as a duplicate of https://github.com/GitJournal/GitJournal/issues/646

**Closed by vHanda** 2022-11-20 20:12 UTC
