### ISSUE TITLE
Feature Request: Passcode Lock

### ISSUE THREAD

**Issue by cyberbobcity** [GitJournal/GitJournal#169] opened 2020-06-29 14:45 UTC
Just started using the app to re-kickstart a journalling habit. I think a great feature for this app would be a simple passcode lock. On iOS you could even use TouchID or FaceID to make it even easier. It doesn't need to be super secure, just something to prevent others who might be using your device from seeing your journal.

**Comment by vHanda** [comment] 2020-07-03 20:22
Makes sense. Will do! Closing this report as it's a duplicate of #28. 

Could you please vote on that issue?

**Closed by vHanda** 2020-07-03 20:22 UTC

**Comment by cyberbobcity** [comment] 2020-07-06 14:39
My apologies, I thought I had searched through the feature requests and didn't see it. Will do.

**Comment by vHanda** [comment] 2020-07-06 14:41
Nothing to apologize about. It barely takes me a few seconds to close them, and the search in github doesn't always find them :)

The important bit is that you keep filing bug reports and feature requests!
