### ISSUE TITLE
Support for archiving notes [Feature request]

### ISSUE THREAD

**Issue by radupotop** [GitJournal/GitJournal#605] opened 2022-02-24 14:43 UTC
It would be incredibly useful if GitJournal had an 'archive note' feature like Google Keep does - so you could keep old notes around without having them in your face all the time.  
It could be done with having a special `Archive` folder where all these notes get moved to, but its contents is ignored by default.  
Thanks.

**Comment by vHanda** [comment] 2022-02-24 19:55
Hello.

Thank you for filling this. I'm closing it as it's a duplicate of https://github.com/GitJournal/GitJournal/issues/387 . Would you mind voting on that issue please? Also I'm not sure what mechanism there should be for archiving -

1. Add 'archived: true' in the YAML MetaData - This doesn't work for markdown files without yaml or txt or other kinds of files.
2. Add a `.archived` folder in the directory where the note exists
3. Add a top level 'Archived' folder and mirror the directory structure - This seems difficult to do as at some point the directory structure is going to go out of sync.

I'm leaning towards (2), as that is the simplest. Also, folders starting with a `.` are already ignored by GitJournal so this will be much easier to implement.

**Closed by vHanda** 2022-02-24 19:55 UTC
