### ISSUE TITLE
Take git file creation/modification date into account when sorting

### ISSUE THREAD

**Issue by cstuder** [GitJournal/GitJournal#220] opened 2020-08-19 07:41 UTC
## Environment

**App version:** 1.66.0+1654
**Device information:**
 - OS name and version: iOS 13.6.1
 - Manufacturer: Apple
 - Model: iPhone 11

## Description

**What you'd like to happen:**

My markdown file don't have `created`/`modified` tags in them. I automatically assumed that GitJournal looks at the file modification or creation time according to the Git database in order to sort files by "Last modified" and "Created".

Now, sorting by "Last modified" or "Created" just gives me the list of files sorted alphabetically by file name. I initially assumed this is a bug.

**Feature request:**

If no `created`/`modified` tag is found in a file, use the Git log to determine these dates automatically and use them in sort.

**Comment by vHanda** [comment] 2020-08-19 07:44
Marking as a duplicate of #78 

I'm very close to doing this, as without the YAML header, the notes aren't always sorted correctly, and specially since I often edit things just on the terminal, it would be nice for GitJournal to sort the notes correctly.

**Comment by cstuder** [comment] 2020-08-19 07:44
Sorry, just saw that this is a dupliceate of #78.

**Comment by vHanda** [comment] 2020-08-19 07:44
Please vote on that issue

**Closed by vHanda** 2020-08-19 07:44 UTC

**Comment by cstuder** [comment] 2020-08-19 07:45
Will do.

(You were a second faster than me for closing...) :-)
