### ISSUE TITLE
After the last update the program stopped running

### ISSUE THREAD

**Issue by 1001ruchka** [GitJournal/GitJournal#519] opened 2021-07-01 23:41 UTC
App version:**  1.77.1
Device information:**
 - OS name and version: iOS 14.4
 - Model: iPhone SE (1 gen)

After the last update the program stopped running. 
On startup, the screen appears:
**Error on line 60, column 105:
Mapping values are not allowed here.
Did you miss a colon earlier?**

Uninstalling and reinstalling the program does not solve the problem!
![IMG_B662674066EC-1](https://user-images.githubusercontent.com/5934321/124200820-f00e5c80-dade-11eb-92ea-32bd701b0acc.jpeg)

**Comment by 1001ruchka** [comment] 2021-07-02 00:06
https://user-images.githubusercontent.com/5934321/124202124-695b7e80-dae2-11eb-80ac-ca96374c1bdd.MOV

**Comment by vrtmrz** [comment] 2021-07-02 10:38
Looks like 067344775a38a45d225a19ca5de64a01be0c917d[](url) 's russian YAML are released.
(Yes. Line 60,Column 100 has corrupted ':' )
after 6cacfac7bb61e9f4d727ce9ba5bec879f157f56b , It's looks OK and actually does not reproduced in my environment.

**Comment by vrtmrz** [comment] 2021-07-04 00:32
Current TestFlight version(GitJournal 1.77.3+2596) Looks like fixed in Russian locale.

**Comment by vHanda** [comment] 2021-07-04 00:40
Weirdly, Apple took more than 24 hours to approve the beta, and just took 2 hours to approve the release track. So 1.77.4 was available to the public yesterday, and now 1.77.3 has been made available to the testers.

It defeats the point of putting builds on TestFlight for testing.

Anyway, 1.77.4 also has a fix for the error of too many files are open.

**Closed by vHanda** 2021-07-04 00:40 UTC
