### ISSUE TITLE
Fatal error in setup

### ISSUE THREAD

**Issue by edbock** [GitJournal/GitJournal#484] opened 2021-03-26 00:14 UTC
For some reason the app became unresponsive so I did a data wipe and went to reinstall the app.

Both manual and automatic setup fail with the following:

Failed

Not a Git Repository: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal

Any idea what's happening?  Am I doing something wrong?

**Comment by MisterY** [comment] 2021-03-26 00:18
Can you try to use another location for the repository? It will likely have the same result but might be worth a try.

**Comment by edbock** [comment] 2021-03-27 01:45
I can try another location.  The thing is, the repository I was connected to (my Obsidian notes) was working until a day or two ago.  That's what I want to connect to.

**Comment by edbock** [comment] 2021-03-27 17:13
I went through the setup process again and let it create a new repository "journal."  It worked.  However, I want to connect it to my Obsidian repository instead.  How do I do that?

When I installed the app the first time it took me a long time to get Gitjournal to communicate with my Obsidian repo instead of creating a new one called journal.  Unfortunately I didn't document how I made it work, and I am hoping someone else might help me through the steps.

**Comment by MisterY** [comment] 2021-03-27 18:01
You can try the option in the settings, to select the location.
Then check the logs and add the relevant part, usually the exception message. I suspect there could be a difference between the access permissions for the internal storage and the sd card.
I don't know what Obsidian is, I'm sorry.

**Comment by vHanda** [comment] 2021-03-27 19:08
You don't seem to be the only one with this. I can't seem to reproduce it. I'll try to look into it more tomorrow.

**Comment by edbock** [comment] 2021-03-28 00:17
@vHanda Thanks.  I'm not in a hurry.  I'm thinking it might be a new bug.

By the way, thank you for developing this app.  It works so well I feel like going back to Evernote (for the time being) is a letdown.

Interestingly, I'm not getting the error anymore.  Now everything works up until I get to:

 Cloning...

Now I'm getting the infinite spinning wheel.  I think I've waited about 1/2 hour with no results.  I tried uninstalling/reinstalling with the same results.

@MisterY, Obsidian is an awesome note-taking app for desktop.  I first learned about GitJournal as a way to sync markdown files with both desktop and mobile.  I'm planning on using the combination as a replacement for Evernote.

**Comment by vHanda** [comment] 2021-03-28 01:12
@edbock : Thank you. I really appreciate the praise. I'm not sure about the infinite cloning, could you please attach the debug log (Settings -> Debug). I really have no idea why that is happening.

**Comment by edbock** [comment] 2021-04-02 00:33
Well I've tried over and over and I'm getting the same results.  I'm not getting the error anymore.  When it gets to cloning, I can hit the back button and back my way out.  That's the only thing that works.

However, if I allow GitJournal to create a new repository called "journal" it works fine.  It's only when I try to connect with my existing Obsidian repository that it doesn't work.

The debug log is from after I tried to connect to Obsidian, then backed out of the process after letting the "cloning" process go for about 30 seconds or so.

______________________________
{"t":1617229963106,"l":"i","msg":"--------------------------------","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963107,"l":"i","msg":"--------------------------------","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963108,"l":"i","msg":"--------------------------------","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963108,"l":"i","msg":"--------- App Launched ---------","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963108,"l":"i","msg":"--------------------------------","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963108,"l":"i","msg":"--------------------------------","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963108,"l":"i","msg":"--------------------------------","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963108,"l":"i","msg":"AppSetting {onBoardingCompleted: false, collectUsageStatistics: true, collectCrashReports: true, version: 0, proMode: false, validateProMode: true, proExpirationDate: , pseudoId: 05ff2bde-78a7-43a6-848a-a1b94ddd6731, debugLogLevel: v, experimentalFs: false, experimentalMarkdownToolbar: false, experimentalGraphView: false, experimentalZeroConf: false, experimentalAccounts: false}","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963118,"l":"i","msg":"Running on Android","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}],"p":{"version.securityPatch":"2018-06-01","version.sdkInt":24,"version.release":"7.0","version.previewSdkInt":0,"version.incremental":"16","version.codename":"REL","version.baseOS":"motorola/potter/potter:7.0/NPN25.137-93/11:user/release-keys","board":"msm8953","bootloader":"0xC08A","brand":"motorola","device":"potter","display":"NPNS25.137-93-14","fingerprint":"motorola/potter/potter:7.0/NPNS25.137-93-14/16:user/release-keys","hardware":"qcom","host":"ilclbld32","id":"NPNS25.137-93-14","manufacturer":"motorola","model":"Moto G (5) Plus","product":"potter","supported32BitAbis":["armeabi-v7a","armeabi"],"supported64BitAbis":[],"supportedAbis":["armeabi-v7a","armeabi"],"tags":"release-keys","type":"user","isPhysicalDevice":true,"androidId":"9b5d4b72a6075b82","systemFeatures":["android.hardware.sensor.proximity","com.motorola.motokey.mkprovider","android.hardware.sensor.accelerometer","android.hardware.faketouch","android.hardware.usb.accessory","android.hardware.telephony.cdma","com.motorola.software.storageoptimizer","android.software.backup","com.motorola.software.fmradioservice","android.hardware.touchscreen","android.hardware.touchscreen.multitouch","android.software.print","android.hardware.ethernet","com.motorola.software.x_line","android.software.voice_recognizers","android.hardware.fingerprint","android.hardware.sensor.gyroscope","android.hardware.opengles.aep","com.motorola.motodisplay.6.0","android.hardware.bluetooth","android.hardware.camera.autofocus","android.hardware.telephony.gsm","com.motorola.software.guideme","android.software.sip.voip","android.hardware.usb.host","com.motorola.motokey","android.hardware.audio.output","android.software.verified_boot","android.hardware.camera.flash","android.hardware.camera.front","android.hardware.screen.portrait","com.motorola.motodisplay.doze.glimpse","com.motorola.software.modality","com.nxp.mifare","android.hardware.sensor.stepdetector","android.software.home_screen","com.motorola.actions.2017","android.hardware.microphone","com.motorola.software.device.potter","com.motorola.software.product.potter_retail","com.motorola.moto.value","com.google.preload_photos","android.software.vr.mode","android.hardware.bluetooth_le","android.hardware.sensor.compass","android.hardware.touchscreen.multitouch.jazzhand","android.software.app_widgets","android.software.input_methods","com.motorola.sensorhub.stml0xx","android.hardware.sensor.light","android.hardware.vulkan.version","android.software.device_admin","android.hardware.camera","android.hardware.screen.landscape","com.motorola.software.DirectedSMSProxy","com.motorola.hardware.tier.G","android.software.managed_users","com.motorola.moto","com.motorola.hardware.wave.2017.1","android.software.webview","android.hardware.sensor.stepcounter","android.hardware.camera.any","android.software.connectionservice","android.hardware.touchscreen.multitouch.distinct","android.hardware.location.network","android.software.sip","com.motorola.msimsettings","android.hardware.wifi.direct","android.software.live_wallpaper","com.motorola.actions","android.hardware.location.gps","android.software.midi","com.motorola.cameraone","com.motorola.easyprefix","android.hardware.wifi","android.hardware.location","android.hardware.vulkan.level","com.motorola.motokey.fpsfallback","android.hardware.telephony",null]}}
{"t":1617229963136,"l":"i","msg":"App Version: 1.75.1","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963138,"l":"i","msg":"App Build Number: 2324","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963139,"l":"d","msg":"Event.AppUpdate","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}],"p":{"version":"1.75.1","previous_app_version":"","app_name":"GitJournal","package_name":"io.gitjournal.gitjournal","build_number":"2324"}}
{"t":1617229963151,"l":"d","msg":"Analytics Collection: true","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963156,"l":"i","msg":"Repo Ids [0]","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963157,"l":"i","msg":"Current Id 0","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963165,"l":"d","msg":"Event.Settings","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}],"p":{"noteFileNameFormat":"FromTitle","journalNoteFileNameFormat":"FromTitle","yamlModifiedKey":"modified","yamlCreatedKey":"created","yamlTagsKey":"tags","customMetaData":"","yamlHeaderEnabled":"true","journalEditordefaultNewNoteFolderSpec":"","journalEditorSingleNote":"false","defaultEditor":"Markdown","defaultView":"Standard","sortingField":"Modified","sortingOrder":"desc","remoteSyncFrequency":"automatic","showNoteSummary":"true","folderViewHeaderType":"TitleGenerated","version":"3","markdownDefaultView":"Last Used","markdownLastUsedView":"Edit","homeScreen":"all_notes","theme":"default","themeRasterGraphics":"false","themeOverrideTagLocation":"alt_and_tooltip","doNotThemeTags":"notheme, !nt","doThemeTags":"dotheme, !dt","themeVectorGraphics":"on","themeSvgWithBackground":"false","matchCanvasColor":"true","vectorGraphicsAdjustColors":"all","overlayCaption":"true","transparentCaption":"true","blurBehindCaption":"true","tooltipFirst":"false","useAsCaption":"alt_and_tooltip","doNotCaptionTag":"nocaption, !nc","doCaptionTag":"docaption, !dc","imageLocationSpec":".","zenMode":"false","titleSettings":"h1","swipeToDelete":"true","inlineTagPrefixes":"#","emojiParser":"true","folderName":"journal","bottomMenuBar":"true","confirmDelete":"true","storeInternally":"true","storageLocation":"","sshPublicKey":"false","sshPrivateKey":"false"}}
{"t":1617229963166,"l":"i","msg":"Setting {noteFileNameFormat: FromTitle, journalNoteFileNameFormat: FromTitle, yamlModifiedKey: modified, yamlCreatedKey: created, yamlTagsKey: tags, customMetaData: , yamlHeaderEnabled: true, journalEditordefaultNewNoteFolderSpec: , journalEditorSingleNote: false, defaultEditor: Markdown, defaultView: Standard, sortingField: Modified, sortingOrder: desc, remoteSyncFrequency: automatic, showNoteSummary: true, folderViewHeaderType: TitleGenerated, version: 3, markdownDefaultView: Last Used, markdownLastUsedView: Edit, homeScreen: all_notes, theme: default, themeRasterGraphics: false, themeOverrideTagLocation: alt_and_tooltip, doNotThemeTags: notheme, !nt, doThemeTags: dotheme, !dt, themeVectorGraphics: on, themeSvgWithBackground: false, matchCanvasColor: true, vectorGraphicsAdjustColors: all, overlayCaption: true, transparentCaption: true, blurBehindCaption: true, tooltipFirst: false, useAsCaption: alt_and_tooltip, doNotCaptionTag: nocaption, !nc, doCaptionTag: docaption, !dc, imageLocationSpec: ., zenMode: false, titleSettings: h1, swipeToDelete: true, inlineTagPrefixes: #, emojiParser: true, folderName: journal, bottomMenuBar: true, confirmDelete: true, storeInternally: true, storageLocation: , sshPublicKey: false, sshPrivateKey: false}","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963167,"l":"i","msg":"Loading Repo at path /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963167,"l":"i","msg":"Calling GitInit for journal at: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963291,"l":"d","msg":"Not syncing because RemoteRepo not configured","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963316,"l":"i","msg":"confirmProPurchaseBoot: Pro Mode is false","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963326,"l":"i","msg":"Notes Cache Loaded: 0 items","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963326,"l":"i","msg":"Finished loading the notes cache","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963389,"l":"i","msg":"Notes Cache saving: 0 items","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963430,"l":"i","msg":"Finished loading all the notes","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963535,"l":"d","msg":"Received Share with App (text): null","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229963674,"l":"d","msg":"Event.AppFirstOpen","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}],"p":{"version":"1.75.1","app_name":"GitJournal","package_name":"io.gitjournal.gitjournal","build_number":"2324"}}
{"t":1617229972276,"l":"d","msg":"Event.DrawerSetupGitHost","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229973279,"l":"d","msg":"githostsetup_button_click GitHub","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229973280,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}],"p":{"text":"GitHub","icon_url":"assets/icon/github-icon.png"}}
{"t":1617229974210,"l":"d","msg":"githostsetup_button_click Setup Automatically","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229974210,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}],"p":{"text":"Setup Automatically","icon_url":""}}
{"t":1617229975131,"l":"d","msg":"githostsetup_button_click Authorize GitJournal","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229975132,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}],"p":{"text":"Authorize GitJournal","icon_url":""}}
{"t":1617229975132,"l":"d","msg":"Starting autoconfigure","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229975133,"l":"d","msg":"GitHub: Installed Handler","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229979204,"l":"d","msg":"GitHub: Called onUrl with {URL: gitjournal://login.oauth2?code=cc94d1074bbf09e394c0}","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229979819,"l":"d","msg":"GitHost Initalized: GitHostType.GitHub","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229980355,"l":"d","msg":"Starting RepoSelector","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229980381,"l":"d","msg":"Starting RepoSelector","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229983639,"l":"d","msg":"githostsetup_button_click Next","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229983641,"l":"d","msg":"Event.GitHostSetupButtonClick","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}],"p":{"text":"Next","icon_url":""}}
{"t":1617229983643,"l":"d","msg":"Starting autoconfigure copletion","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229983643,"l":"i","msg":"Generating SSH Key","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229987677,"l":"i","msg":"Generating KeyPair took: 0:00:04.033898","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229987678,"l":"d","msg":"Keys Dir: [/data/user/0/io.gitjournal.gitjournal/code_cache/keysOWXYPM/id_rsa, /data/user/0/io.gitjournal.gitjournal/code_cache/keysOWXYPM/id_rsa.pub]","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229987688,"l":"i","msg":"Adding as a deploy key","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229988321,"l":"d","msg":"GitHub addDeployKey: {\"id\":51694795,\"key\":\"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCwxB0z8eSPemWAANIIysP4dq5SXGjQ7Fed/YnKcre3Lpsa0hWwUBG2nm9UJfIKS2nZ0EIDgERM63167uSpLNpvS/mIPxQNBIV99XyeuZpjURUrQrGJ+lCH2gRy2FL8z06X4/XlOBqfwLzvjzdERS3nYRasqb4Ej4qV0k6HTwWj64Li+r++qfOGPr4Km08LhhDXaVhfUdYd2HSxzOUfxjBQqzEOfsROVAQ2k1xX1d+oaW48o/wuR0Dl6lFSSZU2paOZzubDal3n9sxsr+7Cpd9RIYpbhtxGQ4GXWyydbE5tKxt8xk9rkgUR/lJN/3ehxPiFMmGNDrM1k+Ez5CKVZJ2fX6kcJIeGuca0qdR0sphPXRLbgU9/bHYHHTe3VkOgTbqmRvYZrlEHlIak8HZeAvj9wjvevn9Et18I5cmlxHWIZ2dRM5xyzjgjCuKKTRcLvUJz/7WpvR8UedTNaMITyBS0Ld4v2n4gUrwWKajhkKZJ34n/iO9+LVwfklxYnPhTQnmN9KCbW2cllTrp58HwPxkGqfGRZtYCe6ZYYPGzdH7s875/NWPzsvjFFPWvv1XOZ8TQRiQmSkreekOGUrLLQvS3pxu7Z0vKJcCuJedfBdhG3qOGZ7/ZlKyLWjVqVglwt93/Q6LhLY3I2deMFwZ3BUk6V/mB0/bkuTdOU/pXYedfnw==\",\"url\":\"https://api.github.com/repos/edbock/Obsidian/keys/51694795\",\"title\":\"GitJournal\",\"verified\":true,\"created_at\":\"2021-03-31T22:33:07Z\",\"read_only\":false}","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617229988322,"l":"i","msg":"RepoPath: /data/user/0/io.gitjournal.gitjournal/app_flutter/journal","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617230234506,"l":"d","msg":"Starting RepoSelector","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}
{"t":1617230243294,"l":"i","msg":"Log file /data/user/0/io.gitjournal.gitjournal/cache/logs/2021-03-30.jsonl not found","stack":[{"uri":"unparsed","member":"null","isCore":false,"library":"unparsed","location":"unparsed"}]}

**Comment by edbock** [comment] 2021-05-12 12:59
I use Obsidan (https://obsidian.md/) and the Obsidian Git third party plugin.

The plugin can be installed automatically from within the app.  Settings->Community Plugins
Or you can install it yourself https://github.com/denolehov/obsidian-git

I discovered Obsidian as an alternative to Roam Research (which you should also explore if you haven't already).  Obsidian gives me complete control over my data while Roam keeps it in the cloud.

Obsidian, Roam, and alternatives such as Amplenote and RemNote contain powerful search features and bi-directional note links that make note taking so powerful, I'll never go back.

**Comment by thumos333** [comment] 2021-05-13 19:05
> I use Obsidan (https://obsidian.md/) and the Obsidian Git third party plugin.

Thanks. Obsidian looks really good.

**Comment by edbock** [comment] 2021-09-25 10:34
I think this error happens only when I use external SD card storage.

**Comment by vHanda** [comment] 2022-11-20 20:12
Marking as a duplicate of https://github.com/GitJournal/GitJournal/issues/646

**Closed by vHanda** 2022-11-20 20:12 UTC
Labels: bug
