### ISSUE TITLE
Wiki link autocomplete.

### ISSUE THREAD

**Issue by xlive078** [GitJournal/GitJournal#887] opened 2022-12-20 08:33 UTC
Is possible to add "[[]]" button. And autocomplete with notes which is startswith typing, just like obsidian?

**Comment by vHanda** [comment] 2023-01-19 18:59
Closing as it's a duplicate of https://github.com/GitJournal/GitJournal/discussions/778

**Closed by vHanda** 2023-01-19 18:59 UTC
