### ISSUE TITLE
complete loss of local data on first sync

### ISSUE THREAD

**Issue by edrex** [GitJournal/GitJournal#582] opened 2022-01-09 01:35 UTC
GitJournal silently overwrites local changes rather than attempting to merge them, a behavior I'll guess was introduced as a fix for #473, replacing one data loss mode with another probably less catastrophic one. 

The correct behavior I think is to attempt to merge using one of the default strategies, and if the merge is unsuccessful flag the repo with that. I haven't used the app while synchronizing with other devices yet, but I would hope this is already done when there are changes on both sides?

**Comment by vHanda** [comment] 2022-01-25 13:51
Closing as this is a duplicate of #241

**Closed by vHanda** 2022-01-25 13:51 UTC
