### ISSUE TITLE
Would be nice to be able to customize front matter

### ISSUE THREAD

**Issue by alzxjm** [GitJournal/GitJournal#525] opened 2021-07-11 10:46 UTC
## Environment

**App version:** 1.77.4 Pro
**Device information:** 
 - OS name and version: iOS
 - Manufacturer: Apple
 - Model: iPhone 12 Pro Max

## Description

**What you'd like to happen:** It would be nice to be able to customize how front matter is generated upon new new creation. For example, GitJournal uses the ISO 8601 format for dates:

```
modified: 2021-07-11T06:31:38-04:00
```
and if I want to be able to use a different desktop app such as Dendron, which uses

```
created: 1625999651454
```

it would be convenient to have GitJournal be interoperable.

**Comment by emaynard** [comment] 2021-07-14 01:29
And if I'm not mistaken, in place of modified, Dendron uses the field name **updated.**

**Comment by vHanda** [comment] 2021-07-14 09:31
> And if I'm not mistaken, in place of **modified,** Dendron uses the field name **updated.**

Ah. I've added the option of choosing "updated".

Also closing as it's a duplicate of https://github.com/GitJournal/GitJournal/issues/349

**Closed by vHanda** 2021-07-14 09:32 UTC
