### ISSUE TITLE
Support HTTP/HTTPS URLs

### ISSUE THREAD

**Issue by dmotte** [GitJournal/GitJournal#342] opened 2020-11-13 08:53 UTC
## Environment

**App version:** 1.73.0+2015
**Device information:** (not relevant)

## Description

**What you'd like to happen:** while trying to setup my git remote, I noticed that "only SSH urls are currently accepted". I have a public _Gitea_ server running on HTTPS with a *Let's Encrypt* certificate. It is possible to support also HTTP / HTTPS urls? (in my opinion, this can be a low-priority feature request, since i can temporarily switch to SSH for now)

**Comment by vHanda** [comment] 2020-11-13 09:01
Closing as it's a duplicate of https://github.com/GitJournal/GitJournal/issues/31 . Please vote on that issue :)

**Closed by vHanda** 2020-11-13 09:01 UTC

**Comment by dmotte** [comment] 2020-11-13 09:04
Sorry :sweat_smile: didn't noticed that. Thanks!
