### ISSUE TITLE
Submit to F-droid repo

### ISSUE THREAD

**Issue by mkeedlinger** [GitJournal/GitJournal#106] opened 2020-04-17 00:47 UTC
[F-droid](https://f-droid.org/en/about/) is an Open Source repo and accompanying app for Android.

For those of us who choose to run Android de-googled (ie without Google Play Services) F-droid is one of the best places to get apps <sup>I :heart: Open Source</sup>

[Here](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) is a simple guide from F-droid on how to get apps into the main repository.

<sup><sup>Thanks a ton for your work on this app! It's great!</sup></sup>

**Comment by vHanda** [comment] 2020-04-17 06:46
Hey Michael. I'm going to close this as it's a duplicate of #29. I'll update that issue with the progress that has been made.

**Closed by vHanda** 2020-04-17 06:46 UTC

**Comment by mkeedlinger** [comment] 2020-04-17 16:39
Ah man, I thought I searched well enough for an existing issue! I guess not!

Thanks!
