### ISSUE TITLE
Multi Note selection and Context Menu

### ISSUE THREAD

**Issue by ModProg** [GitJournal/GitJournal#488] opened 2021-04-02 22:47 UTC
Currently, if you long press a note this mode opens where you can share and delete a note. You can't select multiple notes.

![](https://i.imgur.com/Faa6XKv.jpg)

I would propose a popup menu for single Note operations.

![](https://i.imgur.com/A6xwuRI.jpg)

And a button in the top or bottom bar to select multiple.

Or allow selecting multiple when long pressing one, but maybe put actions in a floating action button.

![](https://i.imgur.com/3ci6Pmw.jpg)

**Comment by vHanda** [comment] 2021-05-10 09:14
Closing as it's a duplicate of https://github.com/GitJournal/GitJournal/issues/90

**Closed by vHanda** 2021-05-10 09:14 UTC
